

###
GET http://localhost:3001/api/auth/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmU2MWQzM2U4YjI2NjU2YzY5ZGM0ZCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzA2OTc4MTM2LCJleHAiOjE3MDc1ODI5MzYsInN1YiI6IlRPRE8ifQ.yCDhBrdiMc7R3ChHne4rGo-_lzJZR7FsbIfTScohClI

###
POST http://localhost:3001/api/auth
Content-Type: application/json

{"user_name": "matan", "email": "hello@matan.li", "password": "123456789a", "role": "admin"}

###
POST http://localhost:3001/api/auth
Content-Type: application/json

{"user_name": "abc", "email": "helloa@matan.li", "password": "123456789a", "role": "user"}

###
POST http://localhost:3001/api/auth/sign-in
Accept: application/json
Content-Type: application/json

{"email": "hello@matan.li", "password": "123"}

###
POST http://localhost:3001/api/products
Content-Type: application/json

{ "name": "prod1", "categories": [1, 2], "price": "123", "image_src": "img/3.png", "stock": 1, "description": "something2" }
###
POST http://localhost:3001/api/products
Content-Type: application/json

{ "name": "prod2", "categories": [1], "price": "124", "image_src": "img/4.png", "stock": 0, "description": "something4" }

###
GET http://localhost:3001/api/products
Content-Type: application/json

{}

###
GET http://localhost:3001/api/products/65cf814bd10a6f80dcc1cb32
Content-Type: application/json


###
PUT http://localhost:3001/api/products/65cf814bd10a6f80dcc1cb32
Content-Type: application/json

{"stock": 12}

###
DELETE http://localhost:3001/api/products/65cf814bd10a6f80dcc1cb32
Content-Type: application/json

###
GET http://localhost:3001/api/products?skip=0&limit=0
Content-Type: application/json

{}
