export enum ErrorType {
    DEFAULT_ERROR,
    MISSING_FIELD,
    INVALID_OBJECT_ID,
    INVALID_TYPE,
    DOC_NOT_FOUND,
    WRONG_FILE_TYPE,
    DOC_NOT_UPDATED,
    DOC_NOT_DELETED,
    MUL_ERROR,
    DEDICATED_UPDATE,
    CART_USER_ALREADY_EXIST,
    CART_LOCKED,
}